Reword macOS include_dirs
The used fix no longer worked and it even broke it on Linux
and possibly also somewhere else with:

ValueError: got unknown compilation option, please remove: include_dirs

Fixes https://github.com/cvut/MI-PYT/issues/61